# Copyright 2017 The Gardener Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:  www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: auto-node-repair
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auto-node-repair
    spec:
      containers:
      - name: auto-node-repair
        image: kvmprashanth/auto-node-repair:v4
        imagePullPolicy: Always 
        command:
          - ./auto-node-repair
          - --cloud-provider=aws # Supports only "aws"
          - --nodes=1:5:asg1-name # Name of the auto-scaling-group in Min:Max:ASGName format
          - --nodes=1:5:asg2-name # Name of the auto-scaling-group in Min:Max:ASGName format (multiple)
          - --stderrthreshold=info
          - --kubeconfig=kubeconfig.yaml # Path to kubeconfig file (relative/absolute) could be created using configmaps or secrets
        env:
          - name: AWS_REGION
            value: $AWS_REGION$
          - name: AWS_ACCESS_KEY_ID 
            value: $AWS_ACCESS_KEY_ID$
          - name: AWS_SECRET_ACCESS_KEY
            value: $AWS_SECRET_ACCESS_KEY$
